name: Docker Image Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository (if needed)
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Step 3: Pull Docker image from Docker Hub
      - name: Pull Docker Image
        run: docker pull oluchioraekwe/taskmanger:v5.1

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'oluchioraekwe/taskmanger:v5.1'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      # # Step 4: Install Trivy (Security Scanner)
      # - name: Install Trivy
      #   run: |
      #     sudo apt-get install wget -y
      #     wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.45.1_Linux-64bit.deb
      #     sudo dpkg -i trivy_0.45.1_Linux-64bit.deb

      # # Step 5: Run Trivy Scan on the Docker image
      # - name: Scan Docker Image with Trivy
      #   run: |
      #     trivy image nginx:latest  # Replace 'nginx:latest' with your image
